name: ot-spc-analysis
channels:
    - conda-forge
    - nodefaults
dependencies:
    - numpy
    - xarray
    - matplotlib
    - cartopy
    - shapely
    - scipy
    - seaborn
    - pandas
    - geopandas
    - jupyter
    - jupyterlab
    - netCDF4
